import Head from "next/head";
import Hero from "../components/Hero";
import  Slider  from "../components/Slider";
import { SliderData } from "../components/SliderData";
import Instagram from '../components/Instagram';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Car Show</title>
        <meta name="description" content="Generated by create next app" />
     
      </Head>

      <Hero heading='Capture Moments of Cars' message='Some Good Car Shots'/>
    <Slider slides={SliderData}/>
    <Instagram />
   </div>
  );
}
